"""Generate an application module from a form specification.

``python -m lowcode.generator forms/lunch-order.json`` writes
``lowcode/generated/<slug>.py``: a thin module that embeds the specification and exposes
``submit``, ``rows``, ``export_csv`` and a ``main`` CLI backed by :mod:`lowcode.app`.
The output is deterministic, so regeneration is byte-identical for an unchanged form.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path

from lowcode.schema import FormSpec

GENERATED_DIR = Path(__file__).resolve().parent / "generated"

_TEMPLATE = '''"""{title} — generated by lowcode.generator from {source}. Do not edit."""

from __future__ import annotations

import sys
from collections.abc import Sequence
from datetime import datetime
from typing import Any

from lowcode.app import FormApp
from lowcode.app import main as _run_cli
from lowcode.schema import FormSpec

SPEC = FormSpec.from_dict(
{spec_literal}
)

APP = FormApp(SPEC)


def submit(values: dict[str, Any], *, now: datetime | None = None) -> dict[str, Any]:
    """Submit one {slug} form (validated against SPEC, subject to the cut-off)."""
    return APP.submit(values, now=now)


def rows() -> list[dict[str, Any]]:
    """Every submission stored in this process."""
    return APP.rows()


def export_csv() -> str:
    """The table as CSV text."""
    return APP.export_csv()


def main(argv: Sequence[str] | None = None) -> int:
    """Command line: submit, list, export (persisted in a JSON store)."""
    return _run_cli(SPEC, argv)


if __name__ == "__main__":
    sys.exit(main())
'''


def render(spec: FormSpec, *, source: str) -> str:
    """Render the module source for *spec* (``source`` names the form file)."""
    literal = json.dumps(spec.source, indent=4, sort_keys=True)
    literal = "\n".join("    " + line for line in literal.splitlines())
    literal = literal.replace("true", "True").replace("false", "False").replace("null", "None")
    return _TEMPLATE.format(title=spec.title, source=source, slug=spec.slug, spec_literal=literal)


def generate(form_path: str | Path, out_dir: str | Path = GENERATED_DIR) -> Path:
    """Write the generated module for *form_path* and return its path."""
    form = Path(form_path)
    spec = FormSpec.load(form)
    target = Path(out_dir) / f"{spec.slug}.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    text = render(spec, source=form.as_posix())
    if not target.exists() or target.read_text(encoding="utf-8") != text:
        target.write_text(text, encoding="utf-8")
    return target


def main(argv: Sequence[str] | None = None) -> int:
    """``python -m lowcode.generator FORM [--out-dir DIR]``."""
    parser = argparse.ArgumentParser(prog="lowcode.generator")
    parser.add_argument("form", help="forms/<name>.json")
    parser.add_argument("--out-dir", default=str(GENERATED_DIR))
    args = parser.parse_args(argv)
    print(generate(args.form, args.out_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
