"""LAYER 3 — isolated multi-agent implementation orchestration (ARCHITECTURE.md §6).

The only component that runs agents. Public surface:

* :mod:`aisdlc.orchestration.roles` — :class:`AgentRole`, :class:`RoleProfile`
* :mod:`aisdlc.orchestration.brief` — :class:`AgentBrief`, :func:`build_brief`
* :mod:`aisdlc.orchestration.runner` — :class:`AgentRunner`, :class:`DryRunRunner`,
  :class:`LocalScriptRunner`, :class:`ClaudeCodeRunner`, :class:`LedgerUsageRecorder`
* :mod:`aisdlc.orchestration.worktree` — :class:`WorktreeManager`
* :mod:`aisdlc.orchestration.review` — :class:`IndependentReviewer`
* :mod:`aisdlc.orchestration.handoff` — :class:`HandoffStore`
* :mod:`aisdlc.orchestration.executor` — :class:`Executor`, :class:`RunReport`
"""

from aisdlc.orchestration.brief import AgentBrief, OutputContract, build_brief, enforce_size
from aisdlc.orchestration.executor import (
    ActionChecker,
    Checkpoint,
    CheckpointKind,
    CheckpointOutcome,
    CheckpointRequest,
    Executor,
    ExecutorConfig,
    ExecutorError,
    LocalTierChecker,
    RunOutcome,
    RunReport,
    TaskReport,
    WaveSpec,
    approve_all_checkpoints,
    budget_engine_from_policy,
    check_wave_order,
    deny_all_checkpoints,
    derive_waves,
    load_superseded_evidence,
    router_from_policy,
    run_verification,
    shell_operators,
)
from aisdlc.orchestration.handoff import (
    Handoff,
    HandoffStatus,
    HandoffStep,
    HandoffStore,
    inputs_hash,
    load_handoffs,
    summarize_handoffs,
)
from aisdlc.orchestration.review import (
    FindingDraft,
    IndependentReviewer,
    ReviewResult,
    build_review_brief,
    changed_line_ranges,
    ground_findings,
    parse_findings,
)
from aisdlc.orchestration.roles import (
    ROLE_PROFILES,
    AgentRole,
    RoleProfile,
    default_complexity,
    default_tool_tier,
    orchestration_policy_spec,
    profile_for,
    role_spec,
)
from aisdlc.orchestration.runner import (
    AgentResult,
    AgentRunner,
    AgentUsage,
    ClaudeCodeRunner,
    DryRunRunner,
    LedgerUsageRecorder,
    LocalScriptRunner,
    NullRecorder,
    RunStatus,
    ScriptedOutcome,
    UsageRecorder,
    allowed_tools_for_tier,
    parse_claude_output,
    parse_result_line,
    verification_tool_pattern,
)
from aisdlc.orchestration.worktree import (
    ApplyResult,
    DiffSummary,
    FileChange,
    WorktreeError,
    WorktreeInfo,
    WorktreeManager,
    branch_name,
)

__all__ = [
    "ROLE_PROFILES",
    "ActionChecker",
    "AgentBrief",
    "AgentResult",
    "AgentRole",
    "AgentRunner",
    "AgentUsage",
    "ApplyResult",
    "Checkpoint",
    "CheckpointKind",
    "CheckpointOutcome",
    "CheckpointRequest",
    "ClaudeCodeRunner",
    "DiffSummary",
    "DryRunRunner",
    "Executor",
    "ExecutorConfig",
    "ExecutorError",
    "FileChange",
    "FindingDraft",
    "Handoff",
    "HandoffStatus",
    "HandoffStep",
    "HandoffStore",
    "IndependentReviewer",
    "LedgerUsageRecorder",
    "LocalScriptRunner",
    "LocalTierChecker",
    "NullRecorder",
    "OutputContract",
    "ReviewResult",
    "RoleProfile",
    "RunOutcome",
    "RunReport",
    "RunStatus",
    "ScriptedOutcome",
    "TaskReport",
    "UsageRecorder",
    "WaveSpec",
    "WorktreeError",
    "WorktreeInfo",
    "WorktreeManager",
    "allowed_tools_for_tier",
    "approve_all_checkpoints",
    "branch_name",
    "build_brief",
    "build_review_brief",
    "changed_line_ranges",
    "default_complexity",
    "default_tool_tier",
    "deny_all_checkpoints",
    "derive_waves",
    "enforce_size",
    "ground_findings",
    "inputs_hash",
    "load_handoffs",
    "load_superseded_evidence",
    "budget_engine_from_policy",
    "check_wave_order",
    "shell_operators",
    "verification_tool_pattern",
    "orchestration_policy_spec",
    "parse_claude_output",
    "parse_findings",
    "parse_result_line",
    "profile_for",
    "role_spec",
    "router_from_policy",
    "run_verification",
    "summarize_handoffs",
]
